2025-08-08 13:39:09,724 INFO    MainThread:20300 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /workspace/wandb/run-20250808_133909-h69wbq23/logs/debug.log
2025-08-08 13:39:09,725 INFO    MainThread:20300 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /workspace/wandb/run-20250808_133909-h69wbq23/logs/debug-internal.log
2025-08-08 13:39:09,725 INFO    MainThread:20300 [wandb_init.py:monkeypatch_ipython():622] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x77ca85a553d0>
2025-08-08 13:39:09,726 INFO    MainThread:20300 [wandb_init.py:init():830] calling init triggers
2025-08-08 13:39:09,727 INFO    MainThread:20300 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'arch': 'MobileNetV2', 'epochs': 10, 'batch_size': 64, 'base_lr': 0.0001, 'base_trainable': False, 'dropout': 0.3, '_wandb': {}}
2025-08-08 13:39:09,727 INFO    MainThread:20300 [wandb_init.py:init():871] starting backend
2025-08-08 13:39:09,727 INFO    MainThread:20300 [wandb_init.py:init():874] sending inform_init request
2025-08-08 13:39:09,734 INFO    MainThread:20300 [wandb_init.py:init():882] backend started and connected
2025-08-08 13:39:09,752 INFO    MainThread:20300 [wandb_run.py:_label_probe_notebook():1318] probe notebook
2025-08-08 13:39:09,752 INFO    MainThread:20300 [wandb_run.py:_label_probe_notebook():1328] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-08-08 13:39:09,754 INFO    MainThread:20300 [wandb_init.py:init():953] updated telemetry
2025-08-08 13:39:09,852 INFO    MainThread:20300 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-08 13:39:10,195 INFO    MainThread:20300 [wandb_init.py:init():1029] starting run threads in backend
2025-08-08 13:39:10,385 INFO    MainThread:20300 [wandb_run.py:_console_start():2494] atexit reg
2025-08-08 13:39:10,385 INFO    MainThread:20300 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-08-08 13:39:10,386 INFO    MainThread:20300 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-08-08 13:39:10,388 INFO    MainThread:20300 [wandb_run.py:_redirect():2434] Redirects installed.
2025-08-08 13:39:10,389 INFO    MainThread:20300 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-08 13:40:39,815 INFO    MainThread:20300 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-08-08 13:40:40,387 INFO    MsgRouterThr:20300 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 3 handles.
2025-08-08 13:40:40,959 ERROR   Thread-3 (_watch_pipe_fd):20300 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 2415, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-08-08 13:40:40,962 ERROR   Thread-3 (_watch_pipe_fd):20300 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 2415, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
